version: '3.8'
networks:
  nodejs2024q2-service_default:
    driver: bridge

services:
  app:
    image: lizavetanikiforova/nodejs2024q2-service-app-home-lib
    restart: always
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nodejs2024q2-service_default
    volumes:
      - ./:/app
      - /app/node_modules
    command: ['npm', 'run', 'migrate:start:dev']

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    command:
      ['postgres', '-c', 'logging_collector=true', '-c', 'log_statement=all']
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d home_library_db']
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nodejs2024q2-service_default

volumes:
  postgres:
